### ISSUE TITLE
Unbound versions post August 3 2017 do not reset rrset.bogus stats when called using stats_noreset

### ISSUE THREAD

**Issue by pgporada** [kumina/unbound_exporter#9]
We were seeing the following graph prior to upgrading unbound from 1.4
![pre-upgrade](https://user-images.githubusercontent.com/2382565/42904282-7f1bf256-8aa2-11e8-8492-f460dbb1369a.png)

and once we upgraded to 1.7 we have been seeing the following
![post-upgrade1](https://user-images.githubusercontent.com/2382565/42904921-8be8d696-8aa4-11e8-8855-cda001e50907.png)

Per https://github.com/NLnetLabs/unbound/blob/master/doc/Changelog
```
3 August 2017: Ralph
    - Remove unused iter_env member (ip6arpa_dname)
    - Do not reset rrset.bogus stats when called using stats_noreset.
    - Added stats for queries that have been ratelimited by domain
      recursion.
    - Do not add rrset_bogus and query ratelimiting stats per thread, these
module stats are global.
```

The README.md for unbound_exporter states
```
This exporter connects to Unbounds TLS control socket and sends the stats_noreset command
```

As a result of the unbound change from above, we altered our prometheus query from `unbound_rrset_bogus_total` to `sum(rate(unbound_rrset_bogus_total[$interval]))`. The numbers seem off and I'm not quite sure what the solution is here. Is this something that the unbound exporter should handle depending on the version of unbound? Here's what the graph looks like with the prometheus query change.
![post-upgrade2](https://user-images.githubusercontent.com/2382565/42904926-8edca27e-8aa4-11e8-81e8-644a50cb43a1.png)

**Comment by BartVerc** [comment]
In the Unbound documentation it says:
_num.rrset.bogus_
       The  number  of rrsets marked bogus by the validator.  Increased
       for every RRset inspection that fails.

From this can be concluded that the new implementation in version 1.7 is a counter that is incremented and never reset to zero, which was the case in version 1.4. In the unbound exporter, the metric is also implemented as counter metric, so that is good. 

Since we are not using this metric, I am not sure if this is a good solution.

When you are calculating the rate of this counter metric with interval 5m for example, the amount of rrset bogus messages is 10, the value will be 2. If you multiply that value by the interval time you get 10 again. This is not a nice solution I guess, but it is the closest to your original graph as I could get.
What I did: `rate(bogus[2m])*2`
